Test library updated and example test cases written for backend
Tandem-App-Tuni/Kivako-app-backend pull request #31
Opened 2020-10-30 17:06 UTC by juusohuhtivuo

The test library was changed from Jest to Mocha, and needed updates were made in the package.json file. In addition, some simple test cases were created to the sample.test.js file to demonstrate how testing works.

2020-11-16 16:23 UTC, ShocKwav3 requested changes
Please update the readme file and put instructions of how to run the tests.

2020-11-16 16:23 UTC, ShocKwav3 commented on src/test/sample.test.js
> +})
commit a new line here so git wont complain

2020-11-20 16:36 UTC, janakavishwajith approved these changes
I think it's good to go after @ShocKwav3 suggested changes.

2020-11-22 08:42 UTC, kmtama approved these changes

2020-11-22 20:50 UTC, merged